name: Build and Test Java Application
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run tests
      run: ./gradlew test
